name: Run Wipe Action Script

on:
  push:
    branches:
      - main

jobs:
  run-wipe-action:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: pip install requests

    - name: Run Wipe Action Script
      run: python microsoftGraphApiWipeAction.py
